server.port=5050
server.address=0.0.0.0
spring.datasource.url=jdbc:postgresql://localhost:5432/servermanager
spring.datasource.username=postgres
spring.datasource.password=^&
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional
spring.jpa.hibernate.ddl-auto=none
