server.port=2020
spring.datasource.url=jdbc:postgresql://localhost:5432/servermanager
spring.datasource.username=postgres
spring.datasource.password=0z3onduZ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
