server.port=2021
spring.datasource.url=jdbc:postgresql://localhost:5432/servermanager
spring.datasource.username=roscoe
spring.datasource.password=7TAWwh1S
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
