server.port=2020
spring.datasource.url=jdbc:postgresql://10.249.244.172:5432/servermanager
spring.datasource.username=hellop
spring.datasource.password=0z3onduZ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
